version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
      - .:/gacha  
    ports:
      - "8000:8000"  
    environment:
      - PYTHONDONTWRITEBYTECODE=1  
      - PYTHONUNBUFFERED=1
    depends_on:
      - db 

  db:
    image: postgres:13  
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db

volumes:
  postgres_data:  
